---
# tasks file for k3-setup-role
- name: update packages
  yum:
    name: "*"
    state: latest


- name: Install K3s agent
  shell: >
    curl -sfL https://get.k3s.io | 
    K3S_URL=https://{{ master_public_ip }}:6443
    K3S_TOKEN={{ hostvars[groups['master-node'][0]]['node_token'] }}
    sh -
  tags: worker
